name: Run Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-15

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26.0.1'
        
    - name: Build and Test
      run: |
        xcodebuild test \
          -project AsyncReactorExample.xcodeproj \
          -scheme AsyncReactorExample \
          -destination 'platform=iOS Simulator,name=iPhone 17,OS=latest' \
          -enableCodeCoverage YES \
          | xcpretty && exit ${PIPESTATUS[0]}
